### ISSUE TITLE
Multi-sort?

### ISSUE THREAD

**Issue by lolouk44** [thomasloven/lovelace-auto-entities#101]
Hi Thomas,

Is it possible to have multi sorts?
What I'm thinking / hoping to achieve is to use a wildcard to list all or my openings / lights for example, and sort them by
1) entities that are on first / on top
2) alphabetically by name

Thanks

**Comment by thomasloven** [comment]
Sort first by filter, and then globally.

**Comment by vontrapp** [comment]
That works for 2 sorts, what about third breakfast^H^H^H^H^H^H^H^H^H sorts?

Also the suggested method breaks down if you have 2 filters, you want to globally sort them by 2 methods. The first sort would still leave the 2 filters separated until the global sort applies, messing up the ordering.
