### ISSUE TITLE
Entities still appear in unused entities

### ISSUE THREAD

**Issue by Cirrus94** [thomasloven/lovelace-auto-entities#102]
When I create an auto-entities card, the entities which are shown in the card still appear in the unused entities area. Is there a solution? Thanks.

**Comment by daringer** [comment]
Funny issue, as I have the very same issue with (flex-table-card)[https://github.com/custom-cards/flex-table-card], even worse, as flex-table does not even ensure that `.entities` is an array, the unused entities view crashed more or less, but luckily (these changes)[https://github.com/home-assistant/frontend/blob/master/src/panels/lovelace/common/compute-unused-entities.ts#L47] do fix this bug. (see [here](https://github.com/custom-cards/flex-table-card/issues/5#issuecomment-607143414) for more details) 

Currently my understanding is that _all_ cards, which are somehow dynamically populating their `.entities` will suffer from this drawback! Lovelace is searching unused entities by checking all cards for their `.entites`, but the cards are not *evaluated*, thus e.g., auto-entities & flex-table-card have an empty `.entities` array and lovelace cannot remove these entities from the unused entities view.

@thomasloven can you confirm this? or did I miss-understand this mechanism?

**Comment by thomasloven** [comment]
That's correct. The "unused entities" list does not actually *evaluate* the lovelace interface, but just scans the configuration. As such, dynamically populated entities are missed - and also do not pop in and out of the unused list on state changes.
