### ISSUE TITLE
Feature Request: Delay to remove based on filter

### ISSUE THREAD

**Issue by boojew** [thomasloven/lovelace-auto-entities#117]
ok - so this may be specific to me, but I use the auto-entities card as part of my primary dashboard showing me entities that are in a given state... For example, lights. Its awesome for this. 1 problem I have though, is if my fat fingers accidentally turn a light off - the entity is almost immediately removed from the card - then I have to go root around lovelace to find it. Would be awesome if I could have a delay between a state change and the entity being removed from the card.

Thanks

**Comment by thomasloven** [comment]
Maybe you could put something together with a combination of state and last_changed filters?
