### ISSUE TITLE
auto-entities forcing first lovelace tab to display in one column?

### ISSUE THREAD

**Issue by poldim** [thomasloven/lovelace-auto-entities#119]
Has anyone else experienced their (only) their main tab on their lovelace UI being forced to the left most column?

![image](https://user-images.githubusercontent.com/16869713/84438512-84173880-abeb-11ea-95bf-3764887d049a.png)

![image](https://user-images.githubusercontent.com/16869713/84438173-ef143f80-abea-11ea-8282-8027c55723dc.png)

![image](https://user-images.githubusercontent.com/16869713/84438653-c04a9900-abeb-11ea-89e4-939d00916622.png)

**Comment by thomasloven** [comment]
Is this still an issue?
