### ISSUE TITLE
security issue:  was allowed to display insecure content from

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#122]
using:

```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Media players
    entities:
      - type: custom:auto-entities
        card:
          type: entities
          style: |
            ha-card {
              box-shadow: none;
              margin: 0px -16px 0px -36px;
              }
        filter:
          include:
            - group: group.media_players
          exclude:
            - state: unavailable
```

suddenly causes this to appear in Safari inspector:

```
[Warning] The page at https://mydomain.duckdns.org:port/lovelace/summary_groups was allowed to display insecure content from http://img.youtube.com/vi/L4QC4eyE4NU/sddefault.jpg.

```
and 

```
Mixed Content: The page at 'https://mydomain.duckdns.org:port/lovelace/summary_groups' was loaded over HTTPS, but requested an insecure image 'http://img.youtube.com/vi/L4QC4eyE4NU/sddefault.jpg'. This content should also be served over HTTPS.
```

in Chrome inspector.

I might have checked the Apple_tv's Apple conference app, but wouldn't otherwise know of any link to the Apple dev conf.

Anyways, do we have a security hole in Ha, for this to happen?

please also see: https://community.home-assistant.io/t/do-we-have-a-security-issue/207955

**Comment by KTibow** [comment]
This is unrelated to auto-entities. If you have a plain entity card, it will still show up.  
Basically it gives you the art for the current playing thing, and when Google Cast asked for the art, it gave a `http` URL.
