### ISSUE TITLE
auto-entities reports a 'custom element doesn't exist' while casting using Google Cast integration

### ISSUE THREAD

**Issue by cdeharo** [thomasloven/lovelace-auto-entities#128]
**Describe the bug**
When using the [Google Cast](https://www.home-assistant.io/integrations/cast/#home-assistant-cast) integration to cast the GUI to a device, all the interface shows fine except the auto-entities card, which shows a red box with the error `custom element doesn't exist: auto-entities` inside.

**To Reproduce**
1. Create a `test` view with:
    - An auto-entities card in it
    - A Google Cast card in it:
```yaml
  - type: entities
    entities:
    - type: cast
      name: Test
      view: test
```
2. Navigate to the `test` view from a browser (I use Google Chrome)
3. Press the _Cast_ button and choose an available cast device
4. Press the _Show_ button
5. In the cast device you will see the interface but the `auto-entities` card will appear in read with the error:
```
custom element doesn't exist: auto-entities
```

**Expected behavior**
The `auto-entities` card must be shown in the cast device like other native cards.

**Environment**
HACS version: 1.2.2
Auto-entities version: 16
Home Assistant version: 0.112.4
Supervisor: 229
HassOS: 4.11

**Related links**
* [“custom element doesn’t exist” … but only when casting](https://community.home-assistant.io/t/custom-element-doesnt-exist-but-only-when-casting/140458)
* [Cast stop working in 106.2 #32370](https://github.com/home-assistant/core/issues/32370)
* [Custom element doesn't exist: hui-...](https://github.com/home-assistant/frontend/issues/4984#issuecomment-591077933)

**Comment by ariekraakjr** [comment]
Same problem on home assistant companion on android

**Comment by thomasloven** [comment]
There's good home things will work better in Home Assistant 2022.3.0

**Comment by thomasloven** [comment]
Is this still an issue?

**Comment by cdeharo** [comment]
Nope, it works for me. Closing.
