### ISSUE TITLE
Title when empty

### ISSUE THREAD

**Issue by kloggy** [thomasloven/lovelace-auto-entities#13]
Would it be possible and if yes, would you consider to add an option to change the title when the card is empty.

Specifically, I use it to display the status of the London Underground Lines with problems. If there are no problems I'd like to change the title to reflect that.

This is how it looks now but Id like to say something like "No reported problems" when all lines have a good service.

![image](https://user-images.githubusercontent.com/38220016/55413469-4b002480-5561-11e9-8ece-c9d58e430d4d.png)

**Comment by thomasloven** [comment]
I think Ians Abomination (which I see you already found) is your best bet there, really:
https://community.home-assistant.io/t/100-templatable-lovelace-configurations/105241
