### ISSUE TITLE
How to get the name I put in the Shelly Cloud

### ISSUE THREAD

**Issue by Groovit** [thomasloven/lovelace-auto-entities#130]
Hi,
When I put my Shelly 2.5 in the Shelly Cloud, I rename the device and the entities. Example maindoor 1, maindoor 2 like entities.
When in my Home Assistant, I use the Shelly Cloud discovery for example, impossible to get the names I put in the Shelly Cloud?
I find only id devices : Shelly 2.5 - BCDDC277AC55-1 and Shelly 2.5 - BCDDC277AC55-2

I can add a name at the id entities but for all the entities, like room : sensor.room_shsw_25_bcddc277ac55_2_total_consumption

But I would like to add the specific name for each device and each entity.
So could have for devices : Shelly 2.5 - BCDDC277AC55-1 - maindoor-1 and Shelly 2.5 - BCDDC277AC55-2 - maindoor-2.
And for entities : sensor.room_shsw_25_bcddc277ac55_2_maindoor-2_total_consumption.
So very easy to install a lot of Shelly only with Shelly Cloud.
Is-it possible?

Thanks
Michel

**Comment by thomasloven** [comment]
This is not an auto-entities issue. See the Home Assistant documentation for how to rename entities and devices.
