### ISSUE TITLE
Wildcards filters not working

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-auto-entities#133]
UI editor (HA 0.114.1) removes all quotes during save thus making using wildcards impossible.

Code snippet:

```
filter:
  exclude:
    - entity_id: "sensor.custom_service_*"
```

Save and edit card again:

```
filter:
  exclude:
    - entity_id: sensor.custom_service_*
```

Reference: https://github.com/thomasloven/lovelace-auto-entities#wildcards

Simone

**Comment by chemelli74** [comment]
Hi, did you get chance to check ?

Thank you in advance,

Simone

**Comment by valantur** [comment]
it doesn't work for me either. Last update to this card was on March 15th, so it looks like development is dead.

**Comment by chemelli74** [comment]
@thomasloven , can you be so kind to take a look at this issue ?

Thx in advance,

Simone

**Comment by chemelli74** [comment]
Working on latest HA build

Simone
