### ISSUE TITLE
Duplicated entities with customize parameter

### ISSUE THREAD

**Issue by andbad** [thomasloven/lovelace-auto-entities#143]
I try to make a card with all of switches that mach an entity id but also with a manual entry.
In other words, I want that the card show the switches that I configure (with name and icon) and then the switches that match the filter.
The problem is that also if I set the "unique" option to "true", the enties are duplicated. But if I remove the customizations of the entities ("name" and "icon") the "unique" option works correctly and the card contains only

**This is the card show duplicated entities:**

type: 'custom:auto-entities'
card:
  type: entities
  title: Interruttori
  state_color: true
  show_header_toggle: false
entities:
  - entity: switch.interruttore_lavastoviglie
    name: Lavastoviglie
    icon: 'hass:dishwasher'
  - entity: switch.interruttore_forno
    name: Forno
    icon: 'hass:stove'
  - entity: switch.interruttore_fornello
    name: Fornello
    icon: 'hass:fire'
  - entity: switch.interruttore_leaf
    name: Leaf
    icon: 'hass:car'
  - entity: switch.interruttore_presabagno
    name: Phon/Stufetta
    icon: 'hass:hair-dryer'
  - entity: switch.interruttore_condizionatore_camera
    name: A/C Camera
    icon: 'hass:air-conditioner'
  - entity: switch.interruttore_condizionatore_ingresso
    icon: 'hass:air-conditioner'
    name: A/C Ingresso
filter:
  include:
    - entity_id: switch.interruttore*
unique: true

**This card DO NOT show duplicated entities:**

type: 'custom:auto-entities'
card:
  type: entities
  title: Interruttori
  state_color: true
  show_header_toggle: false
entities:
  - entity: switch.interruttore_lavastoviglie
  - entity: switch.interruttore_forno
  - entity: switch.interruttore_fornello
  - entity: switch.interruttore_leaf
  - entity: switch.interruttore_presabagno
  - entity: switch.interruttore_condizionatore_camera
  - entity: switch.interruttore_condizionatore_ingresso
filter:
  include:
    - entity_id: switch.interruttore*
unique: true

**Comment by danielo515** [comment]
I don't have any pending update and I am getting this same behaviour. Should I manually update or something?

![Uploading image.png…]()

**Comment by danielo515** [comment]
Ok, using `unique: entity` fixed my problem.
Thanks
