### ISSUE TITLE
Support for "options" in case of "template" filter

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-auto-entities#145]
As far as I understood, currently the "options" feature works only with "include" filter.
Is it possible to use it with "template" filter?

**Comment by chrisaljoudi** [comment]
Yeah, ditto—trying to build a `grid` with a template filter and having no luck.

@thomasloven I also tried returning `type: "entity"` as part of each item/dictionary from the template, and surprisingly no luck there either (quickly looked through through the code in `auto-entities` and it looked like that _should_ work, but I must be missing something).

**Comment by thomasloven** [comment]
There's an example in the release notes for the latest version https://github.com/thomasloven/lovelace-auto-entities/releases/tag/1.7.0

**Comment by ildar170975** [comment]
> 
> 
> There's an example in the release notes for the latest version https://github.com/thomasloven/lovelace-auto-entities/releases/tag/1.7.0

Here there are no cases "template + options":

**Comment by thomasloven** [comment]
The last one sets the `name` option of one of the entities.
It doesn't work exactly the same way, but the end results are the same.

**Comment by ildar170975** [comment]
Thank you! I will try to use this method.

**Comment by ohipe** [comment]
it works like a charm!
@thomasloven you are the best!

**Comment by Mariusthvdb** [comment]
sorry to get back on this..
trying to template the options name too, but am stuck with the documented olsution for the object:

```
        filter:
          template: |
            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
            {%- for s in states.scene
              if select == s.object_id.split('_')[:-1]|join('_') or
                 select == s.object_id.split('_')[:-2]|join('_') %}
              {{ {"entity":s.entity_id,
                  "name": s.object_id.split(select +'_')[1]|capitalize|replace('_',' ') } }}
            {%- endfor %}
#        options:
#          type: custom:template-entity-row
#          name: >
#            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
#            {%- for s in states.scene
#              if select == s.object_id.split('_')[:-1]|join('_') or
#                 select == s.object_id.split('_')[:-2]|join('_') %}
#              {{s.object_id.split(select +'_')[1]|capitalize|replace('_',' ')}}
#            {%- endfor %}
```

commented template works fine in dev templates, splitting the string and showing only the ending. I can not find a way to create that in the filter: template construction.
```
Unhandled Promise Rejection: Error: Invalid entity ID at position 0: [{'entity':
```

 If at all possible, could someone please help? Goal is obvious:

<img width="397" alt="Schermafbeelding 2021-11-23 om 15 41 30" src="https://user-images.githubusercontent.com/33354141/143044961-5358ba8f-d1b8-414f-b5d2-f109230524d9.png">

cut 'Living ceiling 3 Wall - ' .....
