### ISSUE TITLE
Filter by attribute containing space in name

### ISSUE THREAD

**Issue by jacekpaszkowski** [thomasloven/lovelace-auto-entities#154]
Hi,

in latest version there is problem with attibutes with spaces. it was fixed some time ago https://github.com/thomasloven/lovelace-auto-entities/issues/61

Could it be fixed?

**Comment by thomasloven** [comment]
I've decided not to fix this.
It would break the ability to repeat options in auto-entities.

Attribute names should not have spaces in them, and that will break other parts of Home Assistant. Better to fix the custom component mentioned in #61.
