### ISSUE TITLE
Filter by device_class?

### ISSUE THREAD

**Issue by fredrikbaberg** [thomasloven/lovelace-auto-entities#16]
Is it possible to filter by device_class?

I just switched to this (together with bar-card) for battery levels and temperatures, and would like to get all temperature sensors by device_class instead of specifying each temperature sensor one by one. The name of my sensors doesn't help, it's Xiaomi Aqara sensors called `sensor.<room>_multi_sensor` and possibly a number afterwards (temperature, air pressure, humidity) which seem to vary for different sensors.

**Comment by thomasloven** [comment]
Yes. `device_class` is an attribute.
