### ISSUE TITLE
Enhancement: Allow linking/drilldown in rules

### ISSUE THREAD

**Issue by DTTerastar** [thomasloven/lovelace-auto-entities#168]
I would like to add a rule with ```<li><a href="/other/dashboard>Text</a></li>``` but right now it html encodes all of the text and you just see the html.  Is is possible to make a rule that links to a detail lovelace dashboard for a drilldown?

**Comment by thomasloven** [comment]
...

...

what?

**Comment by DTTerastar** [comment]
It would be nice if you could click on the rules (16 lights are on for example) to go to another page.

**Comment by thomasloven** [comment]
`tap_action`
