### ISSUE TITLE
state exclude "normal" not working

### ISSUE THREAD

**Issue by blair287** [thomasloven/lovelace-auto-entities#172]
When using exclude state normal it doesnt work tried with '' and "" and after clicking save the quotes disappears and the test normal turns white.

![auto entities](https://user-images.githubusercontent.com/44187409/110370801-0ed67800-8044-11eb-8edc-8717f48f7058.JPG)
![auto entities normal](https://user-images.githubusercontent.com/44187409/110370810-1138d200-8044-11eb-90c4-d82165a360f7.JPG)

**Comment by thomasloven** [comment]
"Normal" is not the state. It's the frontend translation of "off" for battery entites.

Check the state in [![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by blair287** [comment]
> "Normal" is not the state. It's the frontend translation of "off" for battery entites.
> 
> Check the state in [![Open your Home Assistant instance and show your state developer tools.](https://camo.githubusercontent.com/73bd22e94f35bf8dc96867eb43c77c9f188d621057adab857e6fa5c3a0d7c16a/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f646576656c6f7065725f7374617465732e737667)](https://my.home-assistant.io/redirect/developer_states/)

thanks that worked i was being a idiot lol i tried on but of course i should have tried off XD
