### ISSUE TITLE
[Feature Request] Filter by integration

### ISSUE THREAD

**Issue by bigwoof** [thomasloven/lovelace-auto-entities#181]
Would it possible to add a filter for integrations? For example, I have a custom integration that creates more than 100 sensors and it would be nice to have a quick filter that can pull them all into a card.  I can do this with some legwork but a filter based on the integration will make it much easier.

**Comment by thomasloven** [comment]
No. Home Assistant doesn't keep that information.

**Comment by bigwoof** [comment]
OK thanks!

**Comment by Zagitta** [comment]
> 
> 
> No. Home Assistant doesn't keep that information.

Has this changed since your original reply? Because it certainly seems to be able to filter entities by integration now:
![image](https://user-images.githubusercontent.com/865977/121821209-f0fa5e00-cc97-11eb-9f57-acfbbbac44ca.png)

**Comment by thomasloven** [comment]
That's still a bit hit-or-miss with which integrations support it, but I'll consider it.

**Comment by Mearman** [comment]
I was trying to do exactly this earlier

**Comment by arigit** [comment]
+1 on this request. My use case: I want to list zwave devices that have gone MIA for more than X hours  (using zwave-js, all devices coming from this integration are properly tagged as coming from it)
I also want to be able to exclude all entities coming from a specific integration, e.g. Mobile App

**Comment by cburkins** [comment]
This is fairly interesting to me as well.

**Comment by cburkins** [comment]
Not sure I understand the LoveLace Strategy capability yet, but maybe that's an alternative work-around for this need/idea ?

https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-strategy/

**Comment by marcokreeft87** [comment]
How about the 'integration_entities('tuya')' ? That shows entities based on integration

**Comment by thomasloven** [comment]
Added to 1.10.0
