### ISSUE TITLE
Extend unique to also work on friendly_name

### ISSUE THREAD

**Issue by jougs** [thomasloven/lovelace-auto-entities#184]
My home installation heavily relies on ESPHome for all kinds of things (lights, switches, sensors, you name it). ESPHome announces the entities via MQTT discovery and registers each entity twice: once with the MQTT integration (using the configured plain entity name), and once with the ESPHome integration (using the configured name, but suffixed with `_2`). The `friendly_name` of both entities is the same. If I change the state of one, the other will see the exact same state change.

When I'm now trying to use the [_show all lights that are on_ example](https://github.com/thomasloven/lovelace-auto-entities#examples), all lights are listed twice, which I assume is the expected behavior. However, as far as I can see, there's currently no way to remove the duplicates; `unique` does not help, as the `entity_id`s *are* actually different.

My workaround right now is to add an additional `exclude`-type filter removing everything ending in `_2`. However, this (correctly, but unwantedly) also removes anything that might end in `_2` just by accident, not just entities of the type described above. An example are my multiple lights above my dining table dubbed `light.dining_table_1` through `light.dining_table_5`.

Would it be possible to add another "mode" to unique, which works on the `friendly_name` instead of on the `entity_id`? I think that'd be really useful.

**Comment by thomasloven** [comment]
Sounds like you need to fix your ESPHome integration.

This is not the responsibility of auto-entities.
