### ISSUE TITLE
sorting issue with 100% battery level

### ISSUE THREAD

**Issue by mclever** [thomasloven/lovelace-auto-entities#188]
When using the card for battery sorting on state, values with 100% aren't sorted correctly. Batteries with 100% charge are placed at the bottom, seems like they are being sorted like there value is 10 instead of being larger than the other entities.

type: 'custom:auto-entities'
card:
  type: entities
filter:
  include:
    - name: //
      attributes:
        device_class: battery
sort:
  method: state
  reverse: true

**Comment by thomasloven** [comment]
That's what the `numeric:` sorting option is for.
