### ISSUE TITLE
Card does not work perfect in Vertical Stack Cards

### ISSUE THREAD

**Issue by LuckyTriple7** [thomasloven/lovelace-auto-entities#196]
HASS 2015.5.5
Auto Entities 1.9.1

I use 3 Vertical Stack in Cards, however, these are not displayed side by side.
In the second column, the cards are arranged one below the other and not next to one another.

![image](https://user-images.githubusercontent.com/60685158/118942479-0c04d700-b953-11eb-9a4b-60d4025cc0ef.png)

In Version 1.7.0 there is no Problem:

![image](https://user-images.githubusercontent.com/60685158/118942711-440c1a00-b953-11eb-95eb-dae2473fba6b.png)

I reloaded the Page and empty the Browser Cache

**Comment by thomasloven** [comment]
I offer no support for vertical-stack-in-card.
