### ISSUE TITLE
Logs filled with "Received invalid command" errors

### ISSUE THREAD

**Issue by gadgetchnnel** [thomasloven/lovelace-auto-entities#2]
When using this custom card, the logs are filled with the following error (seems to be every few seconds):

> Received invalid command: config/area_registry/list

It doesn't appear to be affecting the functionality, but it is hiding genuine errors.

**Comment by thomasloven** [comment]
Known tradeoff. Warnings should be gone with Home Assistant 0.87 or above. Won't fix.
