### ISSUE TITLE
Is this 'device name' attribute supported ?

### ISSUE THREAD

**Issue by xAPPO** [thomasloven/lovelace-auto-entities#20]
I've implemented HA MQTT auto discovery in another device but fairly new to HA.  Within 'integrations' in HA the entities get created grouped under a parent 'device' - this is working well..  e.g. parent device BackDoor in this screenshot. 

![image](https://user-images.githubusercontent.com/875211/60399270-f8cba100-9b59-11e9-9001-d4985c89db4c.png)

So - can I access this 'BackDoor' device name as some parameter/attribute in auto-entities,  to create a card that contains all the devices entities ?   Not all entities necessarily have 'BackDoor' in their name

Following on from that if I chose to name my devices accordingly e.g 'BackDoor _#'  could I set up auto-entities to find all devices matching `'*_#*'` and auto create separate cards in Lovelace for each device as it gets added via MQTT auto discovery ?

**Comment by thomasloven** [comment]
Partially fixed. Entities can be added based on device. Selecting which device with a glob or regex is not complete yet, though.

**Comment by xAPPO** [comment]
Thanks Thomas I do appreciate you looking at this... 

On 2019-11-07 23:50, Thomas Lovén wrote:

> Partially fixed. Entities can be added based on device. Selecting which device with a glob or regex is not complete yet, though. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/thomasloven/lovelace-auto-entities/issues/20?email_source=notifications&amp;email_token=AAGVVSZSH5AKQLIA6YBFAGTQSSSVZA5CNFSM4H4M5TN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDOHQXQ#issuecomment-551319646
[2]
