### ISSUE TITLE
FR: make input_number behave as slider-entity-row

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#207]
Hey Thomas, 

Ive got a core FR out https://github.com/home-assistant/frontend/discussions/9431 on having a core option to not show decimals when the state is a whole number and will only ever be a whole number, because of configured step.

however, I've found your slider-entity-row to do almost all that we need. Almost. 

More-info still shows the decimal, and I dont think there's much we can do about that.

Secondly, when an input_number is displayed in an auto-entities config it is displayed with the core styling.

Request would be if you could add some logic to auto-entities, to behave like slider-entity-row, in case of input_number?

thanks for having a look, and hopefully considering

some extra info in Discord #frontend here: https://discord.com/channels/330944238910963714/460846676358332417/862270235934326784

**Comment by thomasloven** [comment]
auto-entities finds entities based on some condition. Nothing else.
