### ISSUE TITLE
Question: display last_changed as primary info

### ISSUE THREAD

**Issue by Toukite** [thomasloven/lovelace-auto-entities#213]
Hello,
I have been trying to display the last_changed attribute as primary info instead of secondary_info (instead of the state), but without success for now ...
Could someone help me on this ?

The idea is to reduce the space taken by this card:
![image](https://user-images.githubusercontent.com/42780622/127787004-428499a0-a2b7-4695-b1d7-79094a11e45f.png)

which represent the list of "humanly actionable entities" such as lights sorted by last_changed desc (so the first in the list represent the last thing that was activated)

**Comment by thomasloven** [comment]
This is not the scope of auto-entities.
