### ISSUE TITLE
Filtering using last_updated and last_changed doesn't work

### ISSUE THREAD

**Issue by ptrsconsulting** [thomasloven/lovelace-auto-entities#224]
Hi,

I've spent much time already trying to filter by one of the 2 dates, like in the example, but struggled to see any changes. The entities just disappear whenever I use this attribute filter. Is it a bug or am I doing it wrong? :/ 
![Filtering](https://user-images.githubusercontent.com/14137979/138591028-357dbacc-dc67-47e9-8bc9-ee498ba93572.PNG)

**Comment by GrizzlyAK** [comment]
I also see weird behavior when trying to use just the examples on the Code page. For example, the one for `List the five last triggered motion sensors:` list 5 motion sensors that haven't been activated in a LONG time, not the ones I know have. Also, last_updated and last_changed give the same wrong results. The last_triggered option _seems_ to work, listing 5 of the most recent, but when I trigger a sixth one, it doesn't appear in the list. Perhaps I just don't understand what this card is supposed to do. last_triggered isn't even a real attribute, is it?

I'm having lots of trouble with the filtering too.

**Comment by ndbroadbent** [comment]
Sorry to reply on an old issue, but in case anyone else finds this - @ptrsconsulting The "last_changed" filter is a top-level key, and should not be under attributes. It should be like this:

```
filter:
  include:
    - domain: binary_sensor
      attributes: 
        device_class: motion
      last_changed: '> 1'
```
