### ISSUE TITLE
[Feature Request] Support for new Entity Categorization

### ISSUE THREAD

**Issue by ponchohoncho** [thomasloven/lovelace-auto-entities#227]
The new 2021.11 release has a new feature called Entity Categorization which allows Home Assistant to filter out diagnostic or other non-primary entities from devices

https://developers.home-assistant.io/blog/2021/10/26/config-entity/#entity-categories

Right now Auto Entities cards get every entity, instead of just primary ones. It would be great if we could get rid of the noisy non-primary entities in per-area lists.

**Comment by thomasloven** [comment]
This is added to 1.10.0
