### ISSUE TITLE
Secondary Sorting

### ISSUE THREAD

**Issue by beyondtenor** [thomasloven/lovelace-auto-entities#230]
Would it be, or is it currently, possibly to use a secondary sorting? For instance, I'm using this to track my docker container updates. When an update is available, the entity toggle turns on. I currently sort based on state, which is awesome. It seems the secondary sorting is random, or perhaps it's based on the order the last state changed. It would be awesome to be able to sort based alphabetically after sorting by the state. If it's not something that would be seen as useful to others or simple, I don't want to waste anyone's time.

**Comment by thomasloven** [comment]
There are two sorting options, the per-filter ones are applied first, and the global one second. Use this to your advantage.

**Comment by genem2** [comment]
Hi

I was trying to do the same thing, and came across this post.
Ideally: List all Dockers alphabetically, with the ones that aren't running at the bottom of the list.
I was encouraged by your  per-filter+global response, but I guess I'm not getting it. 

Many thanks.

      type: custom:auto-entities
      show_empty: true
      card:
        title: Dockers
        type: entities
        show_header_toggle: false
      sort:
        method: state                     ## ok, this works...
        numeric: false
        reverse: true
      filter:
        sort: name                       ## Here?
        include:
          - entity_id: switch.docker_*
            sort: name                   ## Here?
            options:
              sort: name                 ## Here?
              type: custom:template-entity-row
              toggle: true
              active: '{{iif(states(config.entity)==''on'', true, false, false)}}'
              secondary: >-
                {{ state_attr(config.entity|replace('switch.',
                'sensor.'),'cpu_percentage') }}% ✦ {{
                state_attr(config.entity|replace('switch.', 'sensor.'),'memory')
                }}Mib

                ({{ state_attr(config.entity|replace('switch.',
                'sensor.'),'status') }})`
