### ISSUE TITLE
FR: template entity and name in filter template

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-auto-entities#232]
trying to template the options name too, but am stuck with the documented solution for the {entity:name} object:

```
        filter:
          template: |
            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
            {%- for s in states.scene
              if select == s.object_id.split('_')[:-1]|join('_') or
                 select == s.object_id.split('_')[:-2]|join('_') %}
              {{ {"entity":s.entity_id,
                  "name": s.object_id.split(select +'_')[1]|capitalize|replace('_',' ') } }}
            {%- endfor %}
#        options:
#          type: custom:template-entity-row
#          name: >
#            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
#            {%- for s in states.scene
#              if select == s.object_id.split('_')[:-1]|join('_') or
#                 select == s.object_id.split('_')[:-2]|join('_') %}
#              {{s.object_id.split(select +'_')[1]|capitalize|replace('_',' ')}}
#            {%- endfor %}
```

commented template works fine in dev templates, splitting the string and showing only the ending. I can not find a way to create that in the filter: template construction.
```
Unhandled Promise Rejection: Error: Invalid entity ID at position 0: [{'entity':
```

Also tried:
```
        filter:
          template: |
            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
            {%- for s in states.scene
              if select == s.object_id.split('_')[:-1]|join('_') or
                 select == s.object_id.split('_')[:-2]|join('_') %}
              {"entity": {{s.entity_id}},
                "name": {{s.object_id.split(select +'_')[1]|capitalize|replace('_',' ')}} }
            {%- endfor %}

```
same result...

 If at all possible, could someone please help? Goal is obvious:

<img width="397" alt="Schermafbeelding 2021-11-23 om 15 41 30" src="https://user-images.githubusercontent.com/33354141/143044961-5358ba8f-d1b8-414f-b5d2-f109230524d9.png">

cut 'Living ceiling 3 Wall - ' .....

the template does exactly that?
<img width="1630" alt="Schermafbeelding 2021-11-24 om 09 39 30" src="https://user-images.githubusercontent.com/33354141/143203590-06573eeb-4730-4e28-a9e4-3c4be41081d8.png">

for reference, this works perfectly:
```
        filter:
          template: |
            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
            {%- for s in states.scene
              if select == s.object_id.split('_')[:-1]|join('_') or
                 select == s.object_id.split('_')[:-2]|join('_') %}
              {{ s.entity_id }}
            {%- endfor %}
```

_Originally posted by @Mariusthvdb in https://github.com/thomasloven/lovelace-auto-entities/issues/145#issuecomment-976647075_

**Comment by Petro31** [comment]
you need to use namespace and return a list if this were even possible.  Not sure if it is.

```
            {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
            {% set ns = namespace(ret=[]) %}
            {%- for s in states.scene
              if select == s.object_id.split('_')[:-1]|join('_') or
                 select == s.object_id.split('_')[:-2]|join('_') %}
              {% set ns.ret = ns.ret + [{"entity":s.entity_id,
                  "name": s.object_id.split(select +'_')[1]|capitalize|replace('_',' ') }] %}
            {%- endfor %}
            {{ ns.ret }}
```

**Comment by Mariusthvdb** [comment]
perfect!

<img width="499" alt="Schermafbeelding 2021-11-24 om 13 22 51" src="https://user-images.githubusercontent.com/33354141/143237728-6fe883d5-8e12-4116-a9cd-2681b2086d40.png">

thank you very much Petro!

**Comment by dibyadip-das** [comment]
> you need to use namespace and return a list if this were even possible. Not sure if it is.
> 
> ```
>             {% set select = states('input_select.hue_group_v2')|lower|replace(' ','_') %}
>             {% set ns = namespace(ret=[]) %}
>             {%- for s in states.scene
>               if select == s.object_id.split('_')[:-1]|join('_') or
>                  select == s.object_id.split('_')[:-2]|join('_') %}
>               {% set ns.ret = ns.ret + [{"entity":s.entity_id,
>                   "name": s.object_id.split(select +'_')[1]|capitalize|replace('_',' ') }] %}
>             {%- endfor %}
>             {{ ns.ret }}
> ```

This works! Thank you @Petro31
