### ISSUE TITLE
[Enhancement] Allow sorting to be "cached" | Only sort on page load

### ISSUE THREAD

**Issue by GaoMax** [thomasloven/lovelace-auto-entities#237]
Hi,
I've been experimenting with auto-entities and it saves so much time! What a great project.
I've encountered one case:
I'm trying the show a list of lights, sorted by its last_changed attribute. Works great.
But I've embedded a button to turn the light on and when I do that, last_changed changes and the list gets sorted again. Would it be possible for sort only to react on page load, and not on entity change? Or is there already an option for this and I missed it?

Thanks a lot!

**Comment by ildar170975** [comment]
> and the list gets sorted again.

If you change some listed entity, then it's `last-changed` is changed too - so the list is supposed to be re-sorted.
There is no option to "ON/OFF" the sorting.

What you can do is (not an easy way):
- use a `template` option for a `filter`;
- provide a template which DOES or DOES NOT sort a list - dependingly on some condition;
- you can use some `input_boolean` for this condition - kind of "switch ON/OFF real-time sorting".

And now think - do these efforts worth it?)))
