### ISSUE TITLE
Do not sort fine positive and negative float numbers

### ISSUE THREAD

**Issue by NapalmCandy** [thomasloven/lovelace-auto-entities#238]
Hi, 

I am trying to sort some float positive and negative numbers, but it do not sort very well
![Captura de pantalla 2021-12-08 a las 22 08 09](https://user-images.githubusercontent.com/12048931/145284774-225072e9-8800-4f79-94f6-319c28b9dd5c.png)

Also the "numeric" tag do not help. It do not sort fine the decimal numbers, but also do not do fine the positive and negative, and worst in my case with all of them together.

**Comment by ildar170975** [comment]
> Also the "numeric" tag do not help,

The `numeric` MUST be used to sort numeric values properly.

> It do not sort fine the decimal numbers,

It works fine for integer & float numbers.

> but also do not do fine the positive and negative,

This is correct. And you issue duplicates this: https://github.com/thomasloven/lovelace-auto-entities/issues/236
