### ISSUE TITLE
Request: Define groups based on auto-entities logic

### ISSUE THREAD

**Issue by LordMike** [thomasloven/lovelace-auto-entities#240]
I maintain some groups such as "all lights" (contrary to the name, it's not _all_ lights, but all ceiling lights for all rooms), "all lights, except entrance", ... and so on.. I have a bunch of these groups, with small variations - mainly for excluding some lights from "all lights". 

What I would like to do, is use Auto-entities logic to create and maintain the groups. Maybe this integration could somehow maintain the groups, or make them on the fly. I've found that a few services exist that allows you to add/remove/replace group memberships.. This could be used in tandem with listeners for new entities (if possible), to maintain groups from some configuration.. :)

I think that'd be cool.. :)

**Comment by thomasloven** [comment]
Auto-entities is a frontend plugin. That means it helps *display* things relating to the internal state of Home Assistant. It does not change anything in it.
