### ISSUE TITLE
Question: sorting numeric and stirng

### ISSUE THREAD

**Issue by KrX3D** [thomasloven/lovelace-auto-entities#252]
Hello,

i got an card for my wast collection. Which sorts right, but when the entrie changes (in 16 Tagen am Mittwoch (09.03.2022))  to tomorrow (Morgen am Dienstag (22.02.2022)) the sorting is wrong:

![image](https://user-images.githubusercontent.com/18599852/154949469-e5df3566-97ca-4002-859c-f8f8d5f84868.png)

my card looks like this;

```type: custom:auto-entities
entities:
  - sensor.biomull
  - sensor.gelber_sack
  - sensor.papiermull
  - sensor.restmull
card:
  type: entities
  title: Abfall
  state_color: true
filter:
  include: []
  exclude: []
sort:
  method: state
  numeric: true
```

so how can i chang it so that tomorrow "Morgen am Dienstag (22.02.2022)" will be on top?

**Comment by KrX3D** [comment]
each time i put it into the "add code" it gets formated like this.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/18599852/154951968-ec444f28-c960-47d4-94b1-30d9155b569d.png)

**Comment by ildar170975** [comment]
> gets formated like this.

Use triple ’

**Comment by ildar170975** [comment]
If these values are sorted as strings then the sorting is OK: “in” comes before “Morgen”.
If these values are sorted as numerical - then the algorithm should be very smart to see dates inside and then sort by dates. Also the first digits “16” may be more than the next date and the sorting may be wrong((((

To avoid this I propose you to do the following (like I did in a similar case):
1) Sort by a numeric attribute. The value should depend on the date. 
2) Since you cannot just add this attribute to the sensor - create template sensors based on the source sensors.

**Comment by KrX3D** [comment]
ok it seems to work now. 

what i did was add to my sensors this "add_days_to: true" so now i get an attribute with the days as int and than i sorted by this attribute:

`
- platform: waste_collection_schedule
  name: Restmüll
  add_days_to: true
  details_format: "upcoming"
  value_template: >
    {% if value.daysTo == 0 %}Heute am {% elif value.daysTo == 1 %}Morgen am {% else %}in {{value.daysTo}} Tagen am {% endif %}
    {% if value.date.strftime("%A") == "Monday" %}Montag{% elif value.date.strftime("%A") == "Tuesday" %}Dienstag{% elif value.date.strftime("%A") == "Wednesday" %}Mittwoch{% elif value.date.strftime("%A") == "Thursday" %}Donnerstag{% elif value.date.strftime("%A") == "Friday" %}Freitag{% elif value.date.strftime("%A") == "Saturday" %}Samstag{% else %}Sonntag{% endif %}
    {{value.date.strftime(" (%d.%m.%Y)")}}
  types:
    - rest`

`type: custom:auto-entities
entities:
  - sensor.biomull
  - sensor.gelber_sack
  - sensor.papiermull
  - sensor.restmull
card:
  type: entities
  title: Abfall
  state_color: true
filter:
  include: []
  exclude: []
sort:
  method: attribute
  numeric: true
  attribute: daysTo
`

**Comment by ildar170975** [comment]
Glad you solved it!
you may close the issue if it is solved
