### ISSUE TITLE
Unable to Download from HACS See image

### ISSUE THREAD

**Issue by cloudbr34k84** [thomasloven/lovelace-auto-entities#253]
![image](https://user-images.githubusercontent.com/58960644/155112602-209ae3e9-5ea8-4645-adbd-8ca9c25ed6fe.png)

**Comment by andrejgorin** [comment]
Have same issue. It's not only cosmetic - download via HACS is really impossible.

**Comment by ildar170975** [comment]
Probably because you a running not 2022.3

**Comment by andrejgorin** [comment]
Last version is 2022.2.9
https://www.home-assistant.io/blog/2022/02/02/release-20222/

**Comment by ildar170975** [comment]
... and this update for the future HA release

**Comment by cloudbr34k84** [comment]
> ... and this update for the future HA release At least as specified in Release notes.

so then how do you download it??

**Comment by ildar170975** [comment]
Seems you cannot unless upgrading to 2022.3 ))

**Comment by ildar170975** [comment]
Guess this issue is outdated and solved.
