### ISSUE TITLE
list of condition is messed up

### ISSUE THREAD

**Issue by cinghialino** [thomasloven/lovelace-auto-entities#259]
I have all the most recent version of Home Assistant and auto-entities, and since the last update of HA this is how I see the conditions:
<img width="978" alt="Screen Shot 2022-03-06 at 5 37 21 PM" src="https://user-images.githubusercontent.com/11861982/156945216-0e5ae894-84d5-4011-8e88-5b3c12f91e13.png">

any suggestion? thank you for your job

**Comment by cinghialino** [comment]
anyone else is experiencing the same problem?

**Comment by aAbdman** [comment]
same Problem here.
it happened after the march update

**Comment by cinghialino** [comment]
You're right! I started noticing it soon after the last 2022.3 update

**Comment by cloudbr34k84** [comment]
yep same here, having the same issue since the update.

**Comment by thomasloven** [comment]
Fixed in 1.11.0
