### ISSUE TITLE
Icon state color not changing

### ISSUE THREAD

**Issue by jordanryle** [thomasloven/lovelace-auto-entities#264]
In the entity's pop-up page, the icon updates color based on state:

![image](https://user-images.githubusercontent.com/4150308/158789755-7e4861fe-9468-4477-95f3-132bcb8da50d.png)

But in the auto-entities card, the icon doesn't update with state:

![image](https://user-images.githubusercontent.com/4150308/158789881-803334c3-4387-4742-a4e8-0a4043982469.png)

**Comment by ildar170975** [comment]
And no code is provided.
Try using the same entity inside a conventional Entities card and read about “state_color” option. 
Then start using custom cards.

**Comment by jordanryle** [comment]
Ok I will close, sorry.

**Comment by ildar170975** [comment]
Please do not apologize.
These kind of issues are better to be discussed in the HA Community first (in the dedicated thread), so GitHub is left for bugs & FRs.
