### ISSUE TITLE
Access to variables in template?

### ISSUE THREAD

**Issue by Inrego** [thomasloven/lovelace-auto-entities#265]
Hi. What variables are available in template?
I'm trying to use the `user` variable, to match by user id, but seems like it's not available.

Here's a very simplified example of what I'm trying to achieve:

```
type: custom:auto-entities
filter:
  template: |
    {% set id = 'input_select.dashboard_1_' ~ user.id %}
    {% set ids = [id] %}
    {% for select_id in ids %}
      {{ select_id }}
    {% endfor %}
card:
  type: entities
```

**Comment by thomasloven** [comment]
`config` and `user` as usual https://www.home-assistant.io/dashboards/markdown/#template-variables
