### ISSUE TITLE
Feature Request: Add configuration option to show/hide hidden entities in core 2022.4+

### ISSUE THREAD

**Issue by krazos** [thomasloven/lovelace-auto-entities#270]
Core 2022.4 introduced a new option to hide entities from the frontend, etc. without disabling them, and it would be great to have a configuration option to hide those hidden entities in the auto-entities card.

For example, I am using the new Switch as X feature to convert several fans on smart switches to fan entities, which automatically hides the original switch entities.  If I then create an auto-entities card with filter groups for both fans and switches, I would like the card to respect the "hidden" property for those switches rather than showing duplicate rows for both the fan and switch entities.

![Screenshot from 2022-04-01 12-00-01](https://user-images.githubusercontent.com/18428022/161542388-4899cb42-131e-4bac-9253-b0986673e0cb.png)

**Comment by igorsantos07** [comment]
@krazos would you close the issue? It's been fixed shortly after your request.

**Comment by krazos** [comment]
Closed as completed.
