### ISSUE TITLE
HA 2022.4 card disappears on save

### ISSUE THREAD

**Issue by ElStupid** [thomasloven/lovelace-auto-entities#271]
Just updated HA to the new 2022.4.
Wanted to update some auto-entities cards, but when I save the card disappears all together. 
Anyone experiencing the same issues? Could it have anything to do with renaming "lovelace" to "dashboards"?

Here's my error

```
Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190
First occurred: 21:06:05 (2 occurrences)
Last logged: 21:08:27

http://homeassistant.local:8123/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841110:1:30990 Uncaught TypeError: Cannot assign to read only property 'filter' of object '#<Object>'
```

**Comment by ildar170975** [comment]
For test, I created some auto-entities card via UI & specified "entity_id: device_tracker.life360*".
The card was created and saved when I closed the window.

**Comment by ElStupid** [comment]
The problem is gone after installing 2022.4.1
Don't know what caused it
