### ISSUE TITLE
Does not respect new "hidden" entity Advanced Option

### ISSUE THREAD

**Issue by nickh66** [thomasloven/lovelace-auto-entities#272]
With the 2022.4 release there is now a new "switch at x" helper and the original switch entities can now be "hidden" from the UI.  However it seems these entities still show in my Dashboard.  I think some modification might be needed to either automatically 'exclude' any hidden entities or add a new filter option to exclude them.

**Comment by KrijnErmerins** [comment]
This would be a great improvement!!

**Comment by sam-ward** [comment]
I was going to log this as a feature request, as this would be extremely handy.

I had hoped that the "hidden" flag would have been exposed as an attribute on the entity (which we could then filter on), but it doesnt seem so.

**Comment by EDelsman** [comment]
I would like a way to filter out hidden entities in the auto-entities card as well, and/or have it do so by default.

**Comment by tboyce021** [comment]
I would vote for just excluding them by default. To me, auto-entities is essentially part of a DIY auto generated dashboard (just in card form) and I imagine the whole point of the "hidden" option is to keep things out of auto generated dashboards. However, if that creates more problems than it solves then I wouldn't complain about an extra filter option to handle it.

**Comment by bjeanes** [comment]
Duplicate of #270 but +1

**Comment by VimalO** [comment]
Would be a useful feature to be able to exclude those hidden entitites

**Comment by JSteeleIR** [comment]
Would love to see progress on this.

I have several entities that I've now use the "show as X" helper on, and they show up as "duplicates" in my auto-entities populated cards, with no seeming way to filter them out.

**Comment by vdbrink** [comment]
I can't remove some items from HA only hide them. It will be very nice to exclude them here also.

**Comment by teskanoo** [comment]
Thank you for addressing this feature request in the latest release :)

**Comment by thomasloven** [comment]
Fixed by #277
