### ISSUE TITLE
Exclude state filter on 'off' doesn't apply to 'unavailable' devices

### ISSUE THREAD

**Issue by alexruffell** [thomasloven/lovelace-auto-entities#285]
``I am not sure this is a bug but figured I should report it in case it is. I am using logbook card to show past states of certain sensors and while trying to make it more legible, I filtered out "off" states. As shown below one of my sensors was not getting filtered out and I believe that is because currently it is 'unavailable'.  When I forced it 'on' it shows as desired, when I force it 'off' it is hidden as desired, and when it went back to 'unavailable' on its own, it was now only showing 'unavailable' instead of the other off states shown in the screenshots below.

Is all this normal or could there be a bug?

<img width="766" alt="image" src="https://user-images.githubusercontent.com/4006944/169547437-a42e57bd-dac5-4128-93b9-2d952b12a827.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/4006944/169547307-b90c286d-5914-4eb8-8b57-fed09962811d.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4006944/169550299-c23e04d7-6275-4906-a11b-db00ca26048d.png">

```
type: custom:auto-entities
card:
  type: logbook
  title: Intrusion Detection Log
  style: |
    .card-header {
    font-size: 18px;
    padding: 2px 15px 2px 15px
    }
  hours_to_show: 48
filter:
  include:
    - entity_id: binary_sensor.*_motion_sensor
    - entity_id: binary_sensor.*_(door|lock)
  exclude:
    - entity_id: binary_sensor.fridge_door
    - state: 'off'
   # - state: unavailable
```

**Comment by mvdwetering** [comment]
I think this is expected as 'unavailable' is a state just like 'on' or 'off'. 
So when it is 'unavailable' it is not 'on' and also not 'off' as it is 'unavailable'. 
This is also why the filter for 'off' does not exclude it (since it is 'unavailable', not 'off')
