### ISSUE TITLE
Example using templates not working

### ISSUE THREAD

**Issue by flinthamm** [thomasloven/lovelace-auto-entities#290]
Home Assistant: 2022.6.6
Auto Entities: 1.11.0

The example at the bottom of README.md does not work in it's shorter template form? I'm simply trying to display a list of lights that are currently on and exlude groups, by using rejectattr which works fine in Developer Tools Templates. Something like:
`template: "{{ states.light | rejectattr('attributes.hue_type', 'defined') | rejectattr('attributes.entity_id', 'defined') | selectattr('state', 'eq', 'on') | list }}"` 

However, even if I try the example from the bottom of the README  (i.e. without the rejectattr filters) this fails to work too. Does anyone else have this experience or a solution please?
`template: "{{states.light | selectattr('state', '==', 'on') | list}}"`

**Comment by ildar170975** [comment]
> which works fine in Developer Tools Templates

Are you saying that your 1st example shows a list of entities in Dev tools?
Actually, it cannot - no `map(attribute='entity_id')`.

**Comment by erkr** [comment]
> Here is how to show a list of entity_ids:
> 
> ```
> {{states.light | selectattr('state', '==', 'on') | map(attribute='entity_id') | list}}
> ```

Yes with  adding the map filter it works fine in the Dev Tools. 
But also for me not with the card!!!

**Comment by thomasloven** [comment]
Fixed by #298?
