### ISSUE TITLE
Allow for secondary information

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [thomasloven/lovelace-auto-entities#293]
Hi

I would like to use this card to show all upcomming birthdays using the Anniversaries integration. All works nice and fine, but I would like to be able to show secondary info for each entry (the age on next birthday). I could not see anything to let me provide this. Is this possible or should I use another means to archive my goal to have a list of all upcomming birthdays within the next four weeks in one list?

Thanks

**Comment by ildar170975** [comment]
This issue is neither a bug or a feature request.
I suggest you to ask similar questions in a HA community in a dedicated "auto-entities" thread.
In short - it is probably possible; for details go to that thread, ask a question with necessary details provided.

**Comment by c-mahn** [comment]
Is there already a tread, that can be linked here? I'm very interested in this function, as I'm having a similar issue with providing IP-adresses for my device-trackers automatically to the dashboard. They are also stored as secondary-information.

**Comment by ildar170975** [comment]
> HA community in a dedicated "auto-entities" thread

https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801
