### ISSUE TITLE
Image for Icon

### ISSUE THREAD

**Issue by woempiej** [thomasloven/lovelace-auto-entities#295]
Hello,

Can I add a custom pictures for this card? I don't like the icons.

![afbeelding](https://user-images.githubusercontent.com/62903344/181321616-6d0b74d8-28e8-46a9-9e74-80d6ee7689c8.png)

Like this:

![afbeelding](https://user-images.githubusercontent.com/62903344/181322893-4c634783-f485-453c-8514-7a969c3e9553.png)

![afbeelding](https://user-images.githubusercontent.com/62903344/181324244-fe887d98-59f2-42de-9b47-145d4a7107e7.png)

**Comment by ildar170975** [comment]
Use `options` to define any options supported by the Entities card

**Comment by woempiej** [comment]
Sorry I'm quiet a noob on Github.
Is the "option" thing a tip to reach out to the docs?
Where can I find the auto-entities community?

**Comment by BebeMischa** [comment]
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801

**Comment by ildar170975** [comment]
> Where can I find the auto-entities community?

https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801


> Is the "option" thing a tip to reach out to the docs?

Docs should be always read before using any card)))
[About `options`.](https://github.com/thomasloven/lovelace-auto-entities#filters)

> Sorry I'm quiet a noob on Github.

You shouldn't be since you started dealing with HA.

**Comment by woempiej** [comment]
I did, but can't find the option.
Thanks for the link to the community
