### ISSUE TITLE
How setup opacity : 92% ? 

### ISSUE THREAD

**Issue by VikeDragon** [thomasloven/lovelace-auto-entities#300]
Greetings!
Please help with the card:

                  - type: custom:auto-entities
                    show_empty: true
                    card:
                      type: entities
                    filter:
                      include:
                        - group: group.plant_warn_moisture_scale
                          options:
                            secondary_info: last-changed
                            style: |
                              :host {
                                --paper-item-icon-color:rgb(102,0,202);
                              } 

it is necessary to make it opaque by 92%
For example, this code works :

                 - type: entities
                    style: |
                      ha-card {
                        opacity: 92%;
                      }  
                    entities:
                      - entity: input_boolean.warnings_flowers
                    state_color: true
                    show_header_toggle: false

I tried to insert it in different ways for
         style: |
            ha-card{
               opacity: 92%;
            }
but nothing comes out - I ask for help ...

**Comment by ildar170975** [comment]
Your issue is not about auto-entities, it is about card-mod. 
Also, this is neither a bug nor a FR. 
It’s a question. 
I suggest you to ask similar questions in a Community forum and leave GitHub for bugs and FRs. 
This particular question is much better to be asked in a Community card- mod thread; at leas you will get your solution faster.

**Comment by VikeDragon** [comment]
Thank you for the information. I'll do it, I just thought it could be done in this particular card.
