### ISSUE TITLE
Compare two temperatures?

### ISSUE THREAD

**Issue by elcriuz** [thomasloven/lovelace-auto-entities#305]
I simply can't wrap my head around how to get this working: I have a couple of smart TRVs set up to show me current temperature and the target temperature. Is there a way to auto populate auto-entities to show me the difference of these values?

I got it working with one TRV like this:
`{{(state_attr("climate.t001s", "current_temperature") |float - state_attr("climate.t001s", "temperature")|float)|round(2)}}`

**Comment by ildar170975** [comment]
1. Either create a template sensor & then display it in Entities.
2. Or use template-entity-row with "state = difference".
