### ISSUE TITLE
template not working

### ISSUE THREAD

**Issue by emilianogetino** [thomasloven/lovelace-auto-entities#311]
Hello, I am trying to make a card that shows me the devices that have a Wi-Fi signal below a threshold indicated by an input_number, the code is as follows:

                                    type: custom:auto-entities
                                            show_empty: true
                                            card:
                                              type: entities
                                              title: Low Signal Devices
                                              state_color: true
                                            filter:
                                              include:
                                                - entity_id: sensor.*rssi*
                                                  state: < "{{ states('input_number.signal_level') }}"                                             
                                            sort:
                                              method: state
                                              reverse: true
                                    
no entity is shown, but if I put the level with a number it works, this code:

                                    type: custom:auto-entities
                                            show_empty: true
                                            card:
                                              type: entities
                                              title: Low Signal Devices
                                              state_color: true
                                            filter:
                                              include:
                                                - entity_id: sensor.*rssi*
                                                  state: < -80                                             
                                            sort:
                                              method: state
                                              reverse: true
The input_number gives me negative values ​​between -50 and -100.
What am I doing wrong?
Thank you.

**Comment by ildar170975** [comment]
> state: < "{{ states('input_number.signal_level') }}"

Templates not supported for options.
Use the "template" option.

**Comment by emilianogetino** [comment]
Thanks for your answer, but unfortunately I'm too new yet.
Could you give me an example? point me somewhere to read about it?
Thank you

**Comment by ildar170975** [comment]
Examples may be found here:
https://community.home-assistant.io/t/auto-entities-automatically-fill-cards-with-entities/147801

**Comment by emilianogetino** [comment]
Thank you

**Comment by ildar170975** [comment]
Is the issue still open?

**Comment by ildar170975** [comment]
Your issue is a question. 
It is neither a bug nor a FR. 
I suggest you to post similar question in the Community and leave Github for bugs and FRs.

**Comment by emilianogetino** [comment]
ok, Gracias
