### ISSUE TITLE
Performance issues since 1.0 / 1.1 release

### ISSUE THREAD

**Issue by syphernl** [thomasloven/lovelace-auto-entities#32]
I have a page with a 15 `auto-entities` cards to show various HA status items (e.g. battery overviews, offline devices, automations grouped by type etc).

Since the recent releases the page became _extremely_ sluggish. On my desktop it is barely usable (scrolling very slow) now and on my phone it's even impossible to use. For instance disabling a particular automation simply doesn't work, pressing the toggle doesn't do anything anymore.  Other pages in my setup work just fine, except for this particular page.

This page contains 5x `entities`, 4x `divider` and 15x `auto-entities`. Nothing special that would explain why this page would be so slow.

This particular uses the following configuration:
https://pastebin.com/7LhdyPZr

I did some profiling with Chrome:

![image](https://user-images.githubusercontent.com/639906/68543830-76cb6e80-03bc-11ea-9392-b3c83f1954d9.png)
![image](https://user-images.githubusercontent.com/639906/68543842-86e34e00-03bc-11ea-9839-179bca259b8a.png)

After uninstalling this plugin via HACS the sluggishness on this page went away and scrolling is just fine, which leads me to believe that someting in this plugin is causing this. Or perhaps I'm asking too much of it? It worked fine in older releases, this problem started after upgrading to 1.0 and 1.1.

**Comment by freemann** [comment]
Here also.
I have one "view" which is using the auto-entites card.
When I open this view and keep it open, the Tab is getting really slow and at some point the Tab shows an error "insufficiënt memory".

The browser is the most recent Chrome browser version 78.0.3904.97 (Official build) (64-bits).

**Comment by syphernl** [comment]
Yay! 01e22c1 resolved the performance issues for me!

**Comment by syphernl** [comment]
@thomasloven Actually... After 01e22c1 I am missing 11 instances of auto-entities
