### ISSUE TITLE
Cards stopped working but work again after deletion of some configuration sections

### ISSUE THREAD

**Issue by Toreca** [thomasloven/lovelace-auto-entities#327]
All the auto-entities cards I have in my dashboards had worked perfectly until the last update. Please look at this [video](https://www.youtube.com/watch?v=3htdWcpbZY8) No entities visible and no error shown (so syntax should by ok as it is accepted by the card). If I delete **sort:** section - still no entities. If I delete **show_empty:** row - still no entities. But If I delete **both** the entities appear. I have tried a few other delete variations but so far found only this one working. So now I can have entities shown but not sorted. Maybe I am just doing something wrong. Any help appreciated.

**Comment by michl270** [comment]
I can confirm this issue as it is also occuring on my Home Assistant instance. 
Whenever I delete the parameter "show_empty: false" the cards re-appear.

**Comment by danlo315** [comment]
Confirming same behavior and same fix by removing the show-empty parameter.  Adding the parameter back breaks the card.

**Comment by darkmatter24** [comment]
Similar issue here - I have dashboards with show_empty = false and options on the include filter that change the row to a custom:template-entity-row. 
If I remove either then the card works, but both together and it breaks

**Comment by VikeDragon** [comment]
Similar issue with v1.12.0 her - If you roll back to version 1.10.1, then everything works, on 1.11 it also does not work.

**Comment by daveshow** [comment]
I can confirm the issue as well with 1.12 rollback to version 1.11 it works fine.


```
type: grid
columns: 1
cards:
  - type: custom:auto-entities
    card:
      type: grid
      columns: 2
      square: false
      title: Music
    card_param: cards
    filter:
      include:
        - integration: cast
          state: playing
          options:
            type: custom:mini-media-player
            artwork: cover
            icon: mdi:youtube-subscription
            group: true
            info: scroll
            source: icon
            replace_mute: stop
            toggle_power: false
            hide:
              controls: false
              volume: false
          sort:
            method: name
        - integration: cast
          state: paused
          options:
            type: custom:mini-media-player
            artwork: cover
            group: false
            toggle_power: false
            hide:
              controls: false
              volume: true
          sort:
            method: name
        - integration: cast
          state: 'off'
          options:
            type: custom:mini-media-player
            group: true
            toggle_power: false
            hide:
              controls: true
          sort:
            method: name
      exclude:
        - state: unavailable
        - state: 'off'
      sort:
        method: name
    show_empty: false
    unique: true

```
