### ISSUE TITLE
After version 2, my auto-entities cards just don't show up at all.

### ISSUE THREAD

**Issue by SteveDinn** [thomasloven/lovelace-auto-entities#34]
I upgraded to v2, refreshed, and the cards are just gone. Reverted, and they all came back.

**Comment by caiosweet** [comment]
Same here. with v1.2 show_empty: false with bug. the entity are on and the card not display.
Back to version 1.1 all regular.

Ps. Thank's for your job :0)

**Comment by towerhand** [comment]
Same for me. 1.2 breaks it.

**Comment by h4nc** [comment]
> Same for me 1.2 breaks it so rolled back to 1.1. I'm using safari and iOS App

same here

**Comment by mattsch** [comment]
Same breakage with 1.2, updating card-tools didn't seem to fix anything for me.

**Comment by thomasloven** [comment]
Are you all using `show_empty: false`?

**Comment by thomasloven** [comment]
I see the problem. Will have a fix up in a minute

**Comment by thomasloven** [comment]
Should be fixed now

**Comment by caiosweet** [comment]
Yesser. 👍
