### ISSUE TITLE
better installation information

### ISSUE THREAD

**Issue by felafel** [thomasloven/lovelace-auto-entities#353]
Can someone post a better set of installation steps?  I am a developer and I cannot figure out how to install this thing.  I have added it the way that the linked document explains it, I think, although it seems like that document is outdated.

I get this when I try to use it.
+++++++
Configuration errors detected:
    Custom element not found: auto-entities
+++++++

Thanks in advance

**Comment by labaland** [comment]
> Can someone post a better set of installation steps? I am a developer and I cannot figure out how to install this thing. I have added it the way that the linked document explains it, I think, although it seems like that document is outdated.
> 
> I get this when I try to use it. +++++++ Configuration errors detected: Custom element not found: auto-entities +++++++
> 
> Thanks in advance

see this video how to install hacs, then search for auto entities in hacs :) super ez!

https://www.youtube.com/watch?v=oXaGqjaKbeE

**Comment by felafel** [comment]
I have HACS.  Searching "auto" in Integrations or Frontend results in nothing with "auto entities".

When I chose Explore and Download Repositories and then pasted in the github url, THEN, it was added.
