### ISSUE TITLE
Template does not work with chips

### ISSUE THREAD

**Issue by paularmstrong** [thomasloven/lovelace-auto-entities#356]
I've seen https://github.com/thomasloven/lovelace-auto-entities/issues/247#issuecomment-1365527347, and trying to be able to use the template option with mushroom-chips-card:

```
type: custom:auto-entities
card:
  type: custom:mushroom-chips-card
  alignment: center
card_param: chips
show_empty: false
filter:
  template: |
    {% set options = '{"type":"entity","content_info":"name","use_entity_picture": true}' %}
    {% set items = {
      "camera.front_bicycle": states.binary_sensor.front_bicycle_occupancy.last_changed,
      "camera.front_cat": states.binary_sensor.front_cat_occupancy.last_changed,
      "camera.front_deer": states.binary_sensor.front_deer_occupancy.last_changed,
      "camera.front_dog": states.binary_sensor.front_dog_occupancy.last_changed,
      "camera.front_person": states.binary_sensor.front_person_occupancy.last_changed
    } %}
    {% set delta = now() - timedelta(days = 1) %}
    {% set comma = joiner(',') %} 
    {% for cam, bin in items.items() if delta < bin -%}
      {{ comma() }}{"entity":"{{ cam }}","options":{{options}}}
    {%- endfor %}
unique: true
```

The result? empty output.

When run through home assistant's template playground, here's the output:

```
{"entity":"camera.front_bicycle","options":{"type":"entity","content_info":"name","use_entity_picture": true}},{"entity":"camera.front_cat","options":{"type":"entity","content_info":"name","use_entity_picture": true}},{"entity":"camera.front_deer","options":{"type":"entity","content_info":"name","use_entity_picture": true}},{"entity":"camera.front_dog","options":{"type":"entity","content_info":"name","use_entity_picture": true}},{"entity":"camera.front_person","options":{"type":"entity","content_info":"name","use_entity_picture": true}}
```

Doing a little bit of debugging, it looks like the result of the template is getting split up incorrectly and becomes an array of garbage: 
<img width="1209" alt="Screenshot 2023-04-10 at 12 42 24" src="https://user-images.githubusercontent.com/33297/230983961-3af5cfb1-fd3a-428b-9465-594e3cd207f4.png">

```json
[
  {
    "entity": "[{\"entity\":\"camera.front_bicycle\""
  },
  {
    "entity": "\"options\":{\"type\":\"entity\""
  },
  {
    "entity": "\"content_info\":\"name\""
  },
  {
    "entity": "\"use_entity_picture\":"
  },
  {
    "entity": "true}}"
  },
  {
    "entity": "{\"entity\":\"camera.front_cat\""
  },
  {
    "entity": "{\"entity\":\"camera.front_deer\""
  },
  {
    "entity": "{\"entity\":\"camera.front_dog\""
  },
  {
    "entity": "{\"entity\":\"camera.front_person\""
  },
  {
    "entity": "true}}]"
  }
]
```

**Comment by jack5mikemotown** [comment]
I'm not knowledgeable about the ins and outs here, but I've got chip card working just fine with auto entities. Maybe my card can help you figure out what's up (templating the icon color doesnt work for some reason, unsure why, but everything else works well)
```    type: custom:auto-entities
    card:
      type: custom:mushroom-chips-card
    card_param: chips
    filter:
      template: >-
       {%- set list=(states|selectattr('state','eq' ,'unavailable')|map(attribute='entity_id')|reject('eq', 'switch.lamp')|reject('contains', 'battery')|list)-%}
       {%-
        for entity in list if area_id(entity) != none-%}
          {{
            {
              'type': 'entity',
              'icon': 'mdi:help-circle',
              'icon_color': 'orange',
              'entity': entity,
              'name': state_attr(entity, 'friendly_name'),
              'content_info': 'name',

            }
          }},
        {%- endfor %}
    sort:
      method: state
      numeric: true```

**Comment by paularmstrong** [comment]
Ah, I see, the format is _not_ the same as if you were enumerating in the include filter and the options should not be a sub-object.

This works now:

```
{% set items = {
  "camera.front_bicycle": states.binary_sensor.front_bicycle_occupancy.last_changed,
  "camera.front_cat": states.binary_sensor.front_cat_occupancy.last_changed,
  "camera.front_deer": states.binary_sensor.front_deer_occupancy.last_changed,
  "camera.front_dog": states.binary_sensor.front_dog_occupancy.last_changed,
  "camera.front_person": states.binary_sensor.front_person_occupancy.last_changed
} %}
{% set delta = now() - timedelta(hours = 20) %}
{% set comma = joiner(',') %}
{% for cam, last in items.items() if delta <= last -%}
  {{ comma() }}{{ { "entity": cam, 'type': 'entity', 'content_info': 'name', 'use_entity_picture': true } }}
{%- endfor %}
```

**Comment by camels84** [comment]
I can you help me?

i'm triyng something similar, but doesn't work well.

I have two colunnes to spam the result, but i doesn't work with chip card. 

`type: horizontal-stack
cards:
  - type: custom:auto-entities
    card:
      type: custom:mushroom-chips-card
    card_param: chips
    filter:
      template: >
        {%- set number = states('sensor.luzes_ligadas_rc')|int(default=0)//2+1-%} 

        {%- set lista=(expand(state_attr('light.gupo_luzes_piso_rc', 'entity_id')) |
           selectattr('state','eq', 'on') |
           sort(reverse=true,attribute='name') |
           map(attribute='entity_id') |
           [:number] -%}
           
        {%- for entity in lista if area_id(entity) != none-%}
          {{
            {
              'type': 'entity',
              'entity': entity,
              'name': state_attr(entity, 'friendly_name'),
              'content_info': 'name',
            }
          }},
        {%- endfor %}
           
    sort:
      method: entity_id`

i'm trying to adapt this post but i can't!
I started with the simple template solucion that works (but i need the mushrrom style!! this is the "simple" solution

`type: horizontal-stack
cards:
  - type: custom:auto-entities
    show_empty: true
    card:
      type: entities
    filter:
      template: >
        {% set number = states('sensor.luzes_ligadas_rc')|int(default=0)//2
        %}        

        {{ (expand(state_attr('light.gupo_luzes_piso_rc', 'entity_id')) |
           selectattr('state','eq', 'on') |
           sort(reverse=false,attribute='name') |
           map(attribute='entity_id') |
           list)[:number] }}
    sort:
      method: entity_id
`

sorry to disturb (both), but someone can help me?
