### ISSUE TITLE
Question: Is it possible to display the top consuming entities?

### ISSUE THREAD

**Issue by bumperboy** [thomasloven/lovelace-auto-entities#378]
My purpose is to have in my dashboard a card displaying the top 3 or 5 entities that are consuming the most energy at that moment.

Most of my electric plugs have a power sensor that I'm already displaying in the Energy dashboard but I would like to have a "live" overview of what is consuming the most at the house.

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/2044970/89d7e4e0-3c12-4f11-ae9f-df31914042c4)

Do you think this is possible with the auto-entities integration?

Thank you for your help.

**Comment by skynet01** [comment]
you should ask this in the forum, but yes it's possible you just filter to show only energy devices and then sort from increasing to decreasing.

**Comment by ildar170975** [comment]
GitHub is better to be used for reporting bugs and proposing FRs. Questions should be asked in Community.
