### ISSUE TITLE
[FEATURE REQUEST] - ability to customize (display) 'name' property of entity

### ISSUE THREAD

**Issue by robsonfelix** [thomasloven/lovelace-auto-entities#386]
Is there a way I could customize the name property used to display the entity name?

For example, suppose I have a list of automations that start with 'Confort -', then I would add then dynamically to a card but I would like to remove the 'Confort - ' from the name. If I was to do this manually, this would be possible. But by using the auto entities card, this is not yet available.

An idea would be to have a regular expression that could be applied to the name, for instance.

Would something like this be possible?

**Comment by ildar170975** [comment]
duplicate of https://github.com/thomasloven/lovelace-auto-entities/issues/166

**Comment by robsonfelix** [comment]
thank you !!!!!!!!!!!
