### ISSUE TITLE
sort based on numeric value of state

### ISSUE THREAD

**Issue by airdrummingfool** [thomasloven/lovelace-auto-entities#39]
Hello and thanks for this great module!

I'm using `auto-entities` in many cards, including a card that shows all battery-powered devices. I recently set up sorting based on `state`, but the sort was strange:
![image](https://user-images.githubusercontent.com/631249/68917323-60604280-072f-11ea-8378-945d5f44c47d.png)

I realized that it's doing a straight string comparison (comparing the first digit first, then the second, etc), which doesn't work very well when dealing with numbers.

It would be awesome if the sorting method took numbers into account. I see a few ways this could be added:
1. A separate `numeric_state` sort method to use instead of `state`.
2. A new option to sort numerically (similar to `ignore_case`).
3. In `sort.js`, the `compare()` method could always check if both states can be converted to numbers with `Number()`, and if so, they could be compared numerically.

I'd be happy to submit a PR with my attempt at adding one of these options, but I wanted to check and see if any of these seem like good solutions to you. What do you think?

**Comment by thomasloven** [comment]
Great idea!
I think I like variant 2 the best. That would be very simple to implement too, just `compare(parseFloat(a), parseFloat(b))` more or less...
... and make sure `ignore_case` is false, or it will throw an error..

**Comment by thomasloven** [comment]
Fixed by #43 in acf8fd1
