### ISSUE TITLE
Auto-entities shows entities that are not visible antwhere else

### ISSUE THREAD

**Issue by vingerha** [thomasloven/lovelace-auto-entities#400]
I created a entities card with auto-entities and filtering on geo_location (geojson entities)
It shows entities that were there about 18 hours ago but I cannot find these anywhere else, not in states not in entities
It concerns 16/17/18/66/67, it does filter out the non-available other ones 79/80/81/82/83 (found in 'entities')

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/44190435/2bfdcec9-c841-450b-898c-aa479b1e958c)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/44190435/beba7b57-d107-4aa0-afb4-94663dc48b7a)

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/44190435/846cd2e4-e9c7-4e37-bfbe-7205096ce87e)

**Comment by ildar170975** [comment]
@vingerha 
Do you still observe this behaviour?

**Comment by vingerha** [comment]
Hi, yes I do, from the shot below, the first two can not be found in devtools states nor entities
I am not sure if it is important but these are generated via geojson integration

![image](https://github.com/thomasloven/lovelace-auto-entities/assets/44190435/4eaf10fa-3e57-4fa6-91f7-189eea8b4050)

but they show up via pressing 'e'
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/44190435/722e76ad-b390-42af-98a6-32145de34421)

**Comment by vingerha** [comment]
likely this is  'core' issue

**Comment by vingerha** [comment]
closing it as likely not related to this card
