### ISSUE TITLE
Home Assistant Companion / iOS Java compatibilty issue?

### ISSUE THREAD

**Issue by highground88** [thomasloven/lovelace-auto-entities#42]
Great work, love the card!

I have installed via HACS (latest) and my auto-entities card works well using Chrome on my PC - however, when looking at the same page via the Home Assistant Companion App or iOS Safari on a iPad 4 (iOS 10.3.3, latest available), it shows the red card stating that "Custom element doesn't exist: auto-entities" and then the configuration.

Is this perhaps a javascript problem? And if so, it seems that this is the only custom card that appears to be having issues with it. 
I have tried using: 
```
frontend:
  javascript_version: auto
AND
frontend:
  javascript_version: latest
```

I am using this is the lovelace-ui : 
```
    url: /community_plugin/lovelace-auto-entities/auto-entities.js
  - type: module
```

**Comment by thomasloven** [comment]
Your configuration syntax is weird.
http://thomasloven.com/blog/2018/08/YAML-For-Nonprogrammers/

**Comment by jokerigno** [comment]
Hi, I have same iPad and same issue. But I don't understand @thomasloven question.

In my case plugin is working on every browser except my old iPad.

@highground88 have you solved it?
