### ISSUE TITLE
multiple integrations for a device - not each integration identifier works

### ISSUE THREAD

**Issue by Bastian007** [thomasloven/lovelace-auto-entities#426]
Hi,
I have devices which has more than one integrations linked to it.
When I select as include filter in auto-entity card integration A, the device is not found, but if I select with integration B it is working.

Is only the first integration (internally numbering) working? 
In my case integration A (battery_notes) is not found, but integration B (homematicip_local) is found.

**Comment by danielbrunt57** [comment]
I also use the battery_notes integration and `include:` `- integration: battery_notes` works fine for me.
```
filter:
  include:
    - integration: battery_notes
```
An entity that is governed by multiple integrations will display when I `include:` any one of them.
