### ISSUE TITLE
Not sorting as expected

### ISSUE THREAD

**Issue by MarcEngrie** [thomasloven/lovelace-auto-entities#442]
I am using the HA RecycleApp (cfr: https://github.com/olibos/HomeAssistant-RecycleApp/) to display collecting dates. Using the auto-entities card so I see them in order of upcoming date.
However, when sorting it does not result in the way I expect it. 
As far as I see, each sensor has an attribute 'Days'

![1](https://github.com/thomasloven/lovelace-auto-entities/assets/19575705/a67dbe0b-24e1-410f-ac20-e2e3f6c1ed1e)

Checking each, I note 

```
GFT: 6
PMD: 6
Restfractie: 8
Papier-karton: 27
Glas: 8
```

When configuring the card, it sorts quite well except for 'Papier-karton'. 

![Screenshot 2024-05-22 074644](https://github.com/thomasloven/lovelace-auto-entities/assets/19575705/725026f5-a888-4a15-9555-8ba45cfe9983)

Any idea what I am doing wrong here or what is wrong?

**Comment by ildar170975** [comment]
The attribute's name is `days`.

**Comment by MarcEngrie** [comment]
Oh! yes indeed! misleading in HA. 
Thx!

**Comment by ildar170975** [comment]
Then close the issue if solved.

**Comment by MarcEngrie** [comment]
Ha! OK. sorry
