### ISSUE TITLE
Exclude state "Away" not working 

### ISSUE THREAD

**Issue by Shredder5262** [thomasloven/lovelace-auto-entities#446]
Trying to use exclude - state away , but i don't see a change when using that option, is this a bug?

![2024-05-26 12_13_46-Andrew Overview Dashboard – Home Assistant - Vivaldi](https://github.com/thomasloven/lovelace-auto-entities/assets/59770346/a5391a54-5e7b-4923-b86d-ed21d50e6992)

Here is my card code in it's current state.
![2024-05-26 12_18_17-Andrew Overview Dashboard – Home Assistant - Vivaldi](https://github.com/thomasloven/lovelace-auto-entities/assets/59770346/687a23d4-40cb-4efd-8d62-d969c64d0576)

I would expect several of the top entries to be excluded from this card, but that doesn't happen...
![2024-05-26 12_15_52-Andrew Overview Dashboard – Home Assistant - Vivaldi](https://github.com/thomasloven/lovelace-auto-entities/assets/59770346/0904fede-2419-4c1e-9f02-3671243b0e89)

**Comment by ildar170975** [comment]
State “Away” is a wrong value for device_tracker, it is “not_home” in fact.
