### ISSUE TITLE
showing empty card in grid layout

### ISSUE THREAD

**Issue by lennartschulte** [thomasloven/lovelace-auto-entities#457]
Hello,
for some time now i have the problem that empty cards take space or are not fully hidden even though i have not enabled "show empty card"
any idea on how to fix this? i'm using this card in a grid layout
![image](https://github.com/thomasloven/lovelace-auto-entities/assets/89683004/76590e78-7e57-414c-a7dc-8e88eb7fa1ea)

**Comment by ildar170975** [comment]
Not an auto-entities card issue, this is how Grid works...

**Comment by ildar170975** [comment]
Changes were added into stack-like cards in 2024.7.
Now see other ways to hide an internal completely...

**Comment by lennartschulte** [comment]
Just as I thought. It was working for many months but just recently stopped. Anyone knows about other ways while still maintaining the functionality of a grid layout?

**Comment by ildar170975** [comment]
Define standards card visibility options for this auto-entities card.
You will probably have to create a template binary sensor (list empty -> ON)

**Comment by lennartschulte** [comment]
Sorry for asking but how do I do that?

**Comment by mash2k3** [comment]
Same issue here, after years of no gap for empty cards now after 2024.7 every auto-entities card has a gap

**Comment by joe-sydney** [comment]
Same here... a breaking change.

**Comment by mash2k3** [comment]
Solved my problem by moving from vertical stack card to layout-card, it also has an option for grid view.
my layout settings for spacing:
card_margin: 0px 0px 5px 0px
reflow: true
https://github.com/thomasloven/lovelace-layout-card

**Comment by joe-sydney** [comment]
> Solved my problem by moving from vertical stack card to layout-card, it also has an option for grid view. my layout settings for spacing: card_margin: 0px 0px 5px 0px reflow: true https://github.com/thomasloven/lovelace-layout-card

Works for me! Thanks!

**Comment by lennartschulte** [comment]
I just fixed my issue with the "conditional" card. Not sure why i didn't use it before. It either must have had not the right functions or have not been implemented at all when I set up the grid. So I got a solution, and it seems there is an alternate solution with the layout card. But I will stick to the standard whenever I can. Thanks for the help!!

**Comment by mash2k3** [comment]
> I just fixed my issue with the "conditional" card. Not sure why i didn't use it before. It either must have had not the right functions or have not been implemented at all when I set up the grid. So I got a solution, and it seems there is an alternate solution with the layout card. But I will stick to the standard whenever I can. Thanks for the help!!

I did use conditional card for some cards but some of my filters were to advanced so i had to stick with auto-entities
