### ISSUE TITLE
Still showing unavailable sensors while listed in exclude

### ISSUE THREAD

**Issue by 1mfaasj** [thomasloven/lovelace-auto-entities#466]
Hi
I'm having issues excluding the unavailable sensors, whatever I try it still gives me the unavailable ones. What am I doing wrong?

type: custom:auto-entities
unique: true
show_empty: true
card:
  type: entities
filter:
  template: '{{integration_entities("SLZB-06") }}'
  include:
    - state: available
  exclude:
    - entity_id: camera.*

![image](https://github.com/user-attachments/assets/d1187807-e1b5-4a84-b844-0ef4870e6bb3)

**Comment by ildar170975** [comment]
1. The posted code is unformatted & cannot be properly analysed.
2. You seem to use `template` & `include/exclude` options together which is not supported. You may either use `template`, `include` or `include + exclude`.

**Comment by ildar170975** [comment]
> I removed the template

Since you removed the `template` option - ALL available cameras are shown, not only belonging to this particular integration. Suggest you ether to define a particular integration as a part of `include` or exclude unavailable entities as a part of `template`.
