### ISSUE TITLE
[FR] Ignore `type: divider` when sorting entities in entities card

### ISSUE THREAD

**Issue by AleXSR700** [thomasloven/lovelace-auto-entities#467]
Hello Thomas,

I am hoping that this is something easy enough to fix and something you would agree on being useful.

I would request ignoring `type: divider` when sorting entities in entities cards.

As you can see, as soon as you turn on sorting, the position of the dividers gets messed up and they lose their usefullness.

![chrome_Zy7ITijpzV](https://github.com/user-attachments/assets/7e2b45c2-40c2-4505-92d0-0974ac188550)

Thank you for your consideration.

Alex

**Comment by ildar170975** [comment]
Move “sort” closer to the defined filter.

**Comment by AleXSR700** [comment]
Oh, sort per entity. Such a simple workaround :)
