### ISSUE TITLE
auto-entities card does not work with Microsoft Edge

### ISSUE THREAD

**Issue by m90att** [thomasloven/lovelace-auto-entities#48]
I have a Surface Go running Windows 10 S which has Edge as its only browser.  When I open HA, none of the auto entity cards work.  see below...

![image](https://user-images.githubusercontent.com/56609577/69740283-0e58ed00-1131-11ea-8355-14e53b0277be.png)

I believe that the following log entry is related as it shows up every time I refresh...

```2019-11-27 16:05:16 ERROR (MainThread) [frontend.js.latest.201911196] https://xxxxxxxxxxxxxxxx.duckdns.org:8123/lovelace/all:1:1 Expected identifier, string or number```

I am on version 0.102.2

**Comment by m90att** [comment]
I am on version 0.102.2

**Comment by thomasloven** [comment]
Do other custom lovelae cards work?

**Comment by m90att** [comment]
Yes From: Thomas LovénSent: 08 January 2020 13:30To: thomasloven/lovelace-auto-entitiesCc: m90att; AuthorSubject: Re: [thomasloven/lovelace-auto-entities] auto-entities card does not work with Microsoft Edge (#48) Do other custom lovelae cards work?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by i00** [comment]
> Do other custom lovelae cards work?

Nope

Have tested:
lovelace-card-tools
vertical-stack-in-card
auto-entities

I have created an issue with HA here: https://github.com/home-assistant/home-assistant/issues/30636

**Comment by Pultost** [comment]
Any News on this issue?

**Comment by m90att** [comment]
> Any News on this issue?

FWIW, it only happens in legacy Edge.  The new chromium based Edge is fine.

**Comment by thomasloven** [comment]
That's kind of what I was betting on.

Since the new version works, consider this a wont-fix.

Developers around the world have wasted enough time to give IE/Edge special treatment. There even used to be special services where you could register and review the totaltime spent to make websites work in IE since microsoft refused to comply to standards...

**Comment by i00** [comment]
@m90att ... Technically not "legacy" Edge yet ... since the current release (not beta) is still using their browsing engine.

**Comment by Pultost** [comment]
Ok, i understand. Unfortunately i will be stuck with non chromium edge for quite a while...
