### ISSUE TITLE
Indentation is not as expected

### ISSUE THREAD

**Issue by jamesking420** [thomasloven/lovelace-auto-entities#55]
Hi,

I have the following card set up and it does not work:

https://hastebin.com/qubaveqalo.cs

This doesn't work.  It only works if the last row (battery_level: <=100) is indented by 4 (realtive to the - in the line above, e.g, like this:
https://hastebin.com/imasikacov.cs

I have no idea why, and it seems to be contrary to the example, such as "Show all gps device_trackers with battery level less than 50:", which has the attributes offset by 2 as per normal yaml.

**Comment by thomasloven** [comment]
The typo in the readme has been fixed.
