### ISSUE TITLE
Custom element doesn't exist: auto-entities

### ISSUE THREAD

**Issue by AndyAnka** [thomasloven/lovelace-auto-entities#60]
Hi!
The auto-entity card will be very useful for my configuration but I still won't get it to work. I have implemented the latest version of auto-entities.js and then added   
- type: module
    url: /local/auto-entities.js
in my resources.
I'm using safari on a mac but have also tried chrome.

/Anders

**Comment by thomasloven** [comment]
There's troubleshooting tips in the installation instructions.
