### ISSUE TITLE
Sorting fails

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-auto-entities#65]
The sorting worked when I had one entity at 30% and the rest at 100%. 

Then one entity went from 100% to 90% and the sort order does not work anymore.
I have cleared my browser case, and restarted HA, without luck.

![image](https://user-images.githubusercontent.com/35527507/72091146-cfad7980-330f-11ea-89f7-7db0a2cdbeed.png)

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-auto-entities#sorting-entities

`numeric`
