### ISSUE TITLE
Sort by State Date  

### ISSUE THREAD

**Issue by kaosmagix** [thomasloven/lovelace-auto-entities#66]
I use a custom component for waste collection date sensors for the different fractions. Now I want to use this component to list them in order of the date. The date is the state value. However when using the sort: option
```
    sort:
      method: state
      numeric: true
```
It will sort alphabetically instead. 07-02-2020, 14-01-2020, 20-01-2020

The option numeric: true has no effect

It would be great if we can sort by date as well (maybe by adding an new config option date: true ? )

Thanks for this great component.

**Comment by thomasloven** [comment]
I think it'd be a better idea to ask the developer of your integration to add an attribute to each sensor with a unix timestamp or something. That would also be useful for automations.
