### ISSUE TITLE
After update to v88.1 get red card

### ISSUE THREAD

**Issue by 01kbpatel** [thomasloven/lovelace-auto-entities#7]
All working on v87.1, but upgrading to v88.1 the custom card seems to be broken, have updated to the latest version of the custom-card, without any joy!

![2f79a85b-a6fd-4cbd-a322-f5ed76fcaf0d](https://user-images.githubusercontent.com/23697824/53297005-3ff20000-380f-11e9-92ec-907892d8c5a9.jpeg)

**Comment by berthavekes2** [comment]
Same here

**Comment by thomasloven** [comment]
The readme includes a link to a document with installation instructions which also contain some suggestions on what to do when things suddenly stop working.
Follow that, and if it doesn't help open a new issue including any relevant information revealed by those steps.
