### ISSUE TITLE
Pin entities

### ISSUE THREAD

**Issue by quthla** [thomasloven/lovelace-auto-entities#72]
Is it possible to pin some entities to the top of the list and have the remaining entities sorted?

**Comment by thomasloven** [comment]
Yes, by sorting per filter.

**Comment by quthla** [comment]
But that won't allow pinning some entities to the top while only having the other entities sorted, right?

**Comment by thomasloven** [comment]
Did you try it?
The lights will be at the top, and the switches will be sorted below them.

**Comment by quthla** [comment]
It does indeed work. I missed that you set sort only on the second element.

What I noticed though, it will sort lowercase letters after uppercase. That's probably not intended, I guess?

**Comment by thomasloven** [comment]
That's how computers order letters, and the reason why the `ignore_case` setting exists.
