### ISSUE TITLE
How to compare to date or timestamp attribute

### ISSUE THREAD

**Issue by airdrummingfool** [thomasloven/lovelace-auto-entities#78]
Hello,
zigbee2mqtt provides a `last_seen` attribute, formatted either as a date (`2020-01-20T06:31:08.678Z`) or an epoch timestamp (`1579502698`). I'd like to show all devices that haven't been seen in the past 24 hours based on this attribute (`last_updated` gets changed whenever z2m or HA restarts) - is there a way to do this?

Thanks for this awesome project!

**Comment by chemelli74** [comment]
Hi,

I would like to do something similar.
Get a list of sensors that have a uptime (timestamp) < 8 hours ago.

If it's doable, looking for a suggestion for the template code.

Simone

**Comment by chemelli74** [comment]
Any kind update ?

Simone

**Comment by lorond** [comment]
@chemelli74 use `template`, for example https://github.com/thomasloven/lovelace-auto-entities/pull/177#issuecomment-1118874682
