### ISSUE TITLE
Filtering on state attribute containing JSON

### ISSUE THREAD

**Issue by SteveDinn** [thomasloven/lovelace-auto-entities#8]
Can this card be used to filter based on a state attribute that is a JSON string? Even a "substring" filter would be sufficient.

**Use case:** I have sensors to monitor wireless signal strength for all my TASMOTA devices based on their "STATE" MQTT topic. The JSON gets broken out, but only one level deep. The Wifi node is broken out as 
a state attribute, but remains as JSON. I was hoping to filter these based on the BSSId attribute so I can list them according to the access point they're connected to.

I've tried the following with no success:
```
attributes:
  Wifi.BSSId: 'AP:MA:CA:DD:RE:SS'
  Wifi: '*"BSSId": "AP:MA:CA:DD:RE:SS"*'
```

**Comment by thomasloven** [comment]
Try regex. That's a bit more powerful.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
