### ISSUE TITLE
Template filter for excluding entities

### ISSUE THREAD

**Issue by calebmah** [thomasloven/lovelace-auto-entities#83]
Currently, the filter section `template` allows the creation of a template filter to include entities. It would be great if we could instead use templates to exclude some entities as well.

I'm using auto entities to display an entities card with media player entities that are currently playing. However, I have a (google home) speaker group set up as an entity as well, and when that group is playing, it appears in the card along with all the other speakers, making it very crowded. 

![image](https://user-images.githubusercontent.com/21040892/73772336-eafa9000-47ba-11ea-9517-0a73c4f7e66a.png)

In this case, "Downstairs Speakers" is a group that contains "Dining Room Speaker" and "Living Room Speaker". Ideally, I would use templates to exclude the individual media players when the group speaker entity is playing. Would this be possible? Are there any existing workarounds? Thanks!

**Comment by thomasloven** [comment]
You'll have to write a template that includes only the speakers you want.
