### ISSUE TITLE
Remote Home-Assistant, calendars on remote server

### ISSUE THREAD

**Issue by bjornta** [thomasloven/lovelace-auto-entities#87]
I have Google calendars on remote server using "Remote Home-Assistant" between multiple servers where the main server does not have any native integrations or plugins other than "auto-entitis".

I get this message:

"The calendar can't be loaded from Home Assistant component."

The same calendar worked fine when the calendar-integration was on the same server.

**Comment by thomasloven** [comment]
What makes you think this has anything at all to do with auto-entities?
