### ISSUE TITLE
Icons sometimes not visible if using customize.yaml to change icon of entity

### ISSUE THREAD

**Issue by janitza-bjag** [thomasloven/lovelace-auto-entities#90]
Hi,

I noticed icons randomly wont displayed on auto-entities card if using customize.yaml to define other icons there. (Text is always displayed, but icons sometimes not)

Can you imagine where the problem is?

with best regards

**Comment by thomasloven** [comment]
I do not believe this is related to auto-entities.
It's not auto-entities which handles displaying the icons, but whatever card you put in `card:.
