### ISSUE TITLE
when using 'custom:slider-entitiy-row' as card in auto-entities, there is a Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Noctris** [thomasloven/lovelace-auto-entities#91]
Hi,

First off all, all praise to the amazing custom cards you have done. I have been using HA for a while now and your cards are awesome.

As for this issue, i wanted to use auto-entities because it is cleaner/nicer then the entities filter and have a slider-entity-row show up if lights are on. I have tried just about every way i could think off but i keep getting an error:

`Cannot read property 'split' of undefined
entities:
  - entity: light.master_bedroom_spots
type: 'custom:slider-entity-row'`

Full code to configure it:

`  - type: "custom:auto-entities"
  card:
      type: "custom:slider-entity-row"
 filter:
   include:
      - entity_id: light.master_bedroom_spots
        state: "on"
  show_empty: false
`

I am more of a backend guy so maybe i missed something really stupid but 134 commits in. I am not seeing it :-s

**Comment by basroovers** [comment]
Same thing here. Using both these cards would be a perfect combination.

```card:
  type: 'custom:slider-entity-row'
  full_row: true
filter:
  include:
    - group: group.slaapkamer_lampen
type: 'custom:auto-entities'```

**Comment by thomasloven** [comment]
slider-entity-row is not a card - as indicated by it's name not containing card and all over the readme.
