### ISSUE TITLE
Support Vertical Stack

### ISSUE THREAD

**Issue by AlexxIT** [thomasloven/lovelace-auto-entities#94]
The option to rename `entities` param to `cards` param will add support Vertical Stack:
![download-1](https://user-images.githubusercontent.com/511909/76228868-63c58f80-6232-11ea-8822-3408709e2789.png)

**Comment by thomasloven** [comment]
This can be done with [layout-card](https://github.com/thomasloven/lovelace-layout-card).

**Comment by golles** [comment]
Hi @thomasloven, 

I've got the same question, could you provide an example of how this could be done with layout-card.

Bedankt!

**Comment by thomasloven** [comment]
It's at the bottom of the layout-card readme file.
