### ISSUE TITLE
Change from websocket to REST api?

### ISSUE THREAD

**Issue by andriej** [thomasloven/lovelace-auto-entities#99]
From what's my current investigation, there problem is connected to websocket, while auto-entities is (what I can see) last custom that uses websocket when problem occurs: https://github.com/home-assistant/frontend/issues/5328

Is it possible to either:
- move code from websocket to REST, which could possibly solve the issue of leaving unused card crashing whole system
- add some additional code to prevent browser from devastating HA?

**Comment by thomasloven** [comment]
I have no idea what you are trying to say.
If you have a problem you believe is caused by auto-entities, please open an issue and present any details which could help me reproduce it.
